apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app  
    spec:
     containers:
      - name: simple-java-app-container
        image: quay.io/cloudbeeci/simple-java-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
     imagePullSecrets:
      - name: quaycred
