apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: simple-java-app-container
          image: quay.io/cloudbeeci/simple-java-app:V1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8085
      imagePullSecrets:
        - name: quay-secret-default-namespace 
---
apiVersion: v1
kind: Service
metadata:
  name: simple-java-app
spec:
  selector:
    app: java-app
  ports:
    - name: http
      port: 8085
      targetPort: 8085
  type: LoadBalancer
