apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app  
    spec:
     containers:
      - name: simple-java-app-container
        image: quay.io/cloudbeeci/simple-java-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
     imagePullSecrets:
      - name: quay-registry-secret
---          
 
apiVersion: v1
kind: Service
metadata:
  name: simple-java-app
  namespace: cloudbeesci-java-app
spec: 
  selector:
   name: java-app
  ports:
   - name: http
     port: 8081
     targetPort: 8081
# For Expose
  type: NodePort
  
